const express = require('express');
const router = express.Router();
const { getAsync, allAsync } = require('../db');
const { authenticateToken, logAuditAction } = require('../middleware/auth');

router.post('/predict-risk', authenticateToken, async (req, res) => {
  try {
    const { importer_name, agent_name, hs_code, declared_value, origin_country, route } = req.body;

    let risk_score = 15;
    const risk_factors = [];

    if (origin_country && ['China', 'Turkey', 'Dubai', 'India'].includes(origin_country)) {
      risk_score += 25;
      risk_factors.push(`High risk origin corridor (${origin_country})`);
    }

    if (hs_code && (hs_code.startsWith('8429') || hs_code.startsWith('9301') || hs_code.startsWith('3004'))) {
      risk_score += 30;
      risk_factors.push(`Sensitive HS Code category (${hs_code})`);
    }

    if (declared_value && declared_value > 20000000) {
      risk_score += 20;
      risk_factors.push(`High monetary declaration value (NGN ${declared_value.toLocaleString()})`);
    }

    if (importer_name) {
      const entity = await getAsync("SELECT * FROM entity_profiles WHERE name ILIKE $1 AND watchlist_status = 'Active'", [`%${importer_name}%`]);
      if (entity) {
        risk_score += 35;
        risk_factors.push(`Importer match on Active CIU Watchlist (${entity.entity_code})`);
      }
    }

    risk_score = Math.min(100, risk_score);
    const recommendation = risk_score >= 75 ? 'RED_LANE_HOLD' : (risk_score >= 45 ? 'YELLOW_LANE_DOC_CHECK' : 'GREEN_LANE_PASS');

    await logAuditAction(req, 'RUN_AI_RISK_PREDICTION', 'AI Prediction Portal', { risk_score, recommendation });

    res.json({
      predicted_risk_score: risk_score,
      risk_category: risk_score >= 75 ? 'Critical Risk' : (risk_score >= 45 ? 'Moderate Risk' : 'Low Risk'),
      recommendation,
      contributing_risk_factors: risk_factors
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/anomaly-detection', authenticateToken, async (req, res) => {
  try {
    const anomalousCargo = await allAsync('SELECT * FROM cargo_profiles WHERE declared_value > 30000000 AND risk_score >= 70');
    const anomalousEntities = await allAsync("SELECT * FROM entity_profiles WHERE watchlist_status = 'Active'");

    res.json({
      detected_anomalies_count: anomalousCargo.length + anomalousEntities.length,
      anomalous_consignments: anomalousCargo,
      anomalous_entities: anomalousEntities,
      detection_algorithm: 'IsolationForest + Rule-Based Anomaly Model v1.4'
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.post('/generate-brief', authenticateToken, async (req, res) => {
  try {
    const { topic, focus_area } = req.body;
    const title = topic || 'National Smuggling & Undervaluation Threat Brief';

    const recentReports = await allAsync("SELECT title, category, command FROM intelligence_reports WHERE status = 'Approved' ORDER BY created_at DESC LIMIT 3");
    const highRiskCargo = await allAsync("SELECT paar_number, importer_name, commodity, selectivity_lane FROM cargo_profiles WHERE selectivity_lane = 'Red' LIMIT 3");

    const generatedBrief = `
# RESTRICTED // CUSTOMS INTELLIGENCE BRIEF
**Topic:** ${title}
**Focus Area:** ${focus_area || 'National Maritime & Border Operations'}
**Generated By:** AI Customs Intelligence Prediction Engine

## 1. Executive Summary
Recent multi-source intelligence correlation indicates increased targeting of high-value machinery and pharmaceutical consignments across maritime terminals.

## 2. Key Actionable Intelligence Signals
${recentReports.map(r => `- [${r.command}] ${r.title} (${r.category})`).join('\n')}

## 3. High Risk Targeted Consignments
${highRiskCargo.map(c => `- PAAR: ${c.paar_number} | Importer: ${c.importer_name} | Commodity: ${c.commodity} [Lane: ${c.selectivity_lane}]`).join('\n')}

## 4. Recommended Directives
1. Issue Red Lane selectivity directives for all matching consignment patterns.
2. Deploy joint CIU-Cybersecurity monitoring team for digital platform impersonations.
    `.trim();

    await logAuditAction(req, 'GENERATE_AI_BRIEF', 'AI Prediction Portal', { topic: title });

    res.json({
      title,
      generated_brief: generatedBrief,
      generated_at: new Date().toISOString()
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
